#Exlample:
#JobName:
# "image": "texture_path"
# "blockid:blockmeta:break": money
Oduncu:
 "image": "textures/blocks/log_oak"
 "17:0:place": 2
 "17:0:break": 2
Madenci:
 "image": "textures/blocks/cobblestone"
 "4:0:break": 1
